version: '3.8'

services:
  service:
    build: .
    container_name: plutocracy-service
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/plutocracy
      - SPRING_DATASOURCE_USERNAME=plutocracy
      - SPRING_DATASOURCE_PASSWORD=plutocracy
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    volumes:
      - ./logs:/var/log/personal-finance-management-system
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/plutocracy/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - plutocracy-network

  postgres:
    image: postgres:14-alpine
    container_name: plutocracy-postgres
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_PASSWORD=plutocracy
      - POSTGRES_USER=plutocracy
      - POSTGRES_DB=plutocracy
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plutocracy"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - plutocracy-network

  redis:
    image: redis:alpine
    container_name: plutocracy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          memory: 256M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - plutocracy-network

  nginx:
    image: nginx:alpine
    container_name: plutocracy-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/share/nginx/html
    depends_on:
      - service
    deploy:
      resources:
        limits:
          memory: 128M
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - plutocracy-network

volumes:
  postgres-data:
  redis-data:

networks:
  plutocracy-network:
    driver: bridge
